trigger:
- master  # Define a branch que acionará o pipeline (substitua 'master' pelo nome da sua branch principal, se necessário)

pool:
  vmImage: 'ubuntu-latest'  # Define a imagem da máquina virtual para a compilação

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Escolha a versão do Python apropriada

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Configurar Ambiente Python'

- script: |
    python -m dados  # Substitua pelo comando de teste real do seu aplicativo
  displayName: 'Executar Testes'

- script: |
    python dados.py  # Substitua pelo comando para executar o aplicativo
    populacao.py
  displayName: 'Executar Aplicativo'

# Aqui você pode adicionar etapas para empacotar seu aplicativo ou implantá-lo em um servidor ou plataforma específica.
